### ISSUE TITLE
404 - https://adr.github.io/madr/

### ISSUE THREAD

**Issue by lemillermicrosoft** [adr/madr#107]
Unable to load user documentation at `https://adr.github.io/madr/` -- 404. Is this a known issue?

```
D:\>curl -I https://adr.github.io/madr/
HTTP/1.1 404 Not Found
```

**Comment by koppor** [comment]
Thank you for reporting. Should have been fixed 5 minutes after you reported the issue.

**Comment by koppor** [comment]
And thank you for choosing MADR 🤩. We will soon release version 4.0.0. Just some polishing (https://github.com/adr/madr/blob/develop/CHANGELOG.md#unreleased and https://github.com/adr/madr/milestone/2). - In case you have some feedback, please let me know!

**Comment by lemillermicrosoft** [comment]
Thanks @koppor! We'll check it out.
