### ISSUE TITLE
"Architectural Decisions" to strengthen "Architecturally Significant"

### ISSUE THREAD

**Issue by koppor** [adr/madr#134]
Short: We think to revert https://github.com/adr/madr/issues/41 to strengthen "Architecturally Significant".

- "Any": Too broad
- "Architectural": Maybe too narrow?

Is going back to "Markdown Architectural Decision Records" a good idea?

**Comment by koppor** [comment]
Note: [spotify backstage](https://backstage.io/docs/architecture-decisions/) uses `docs/architecture-decisions` as path.

**Comment by jonthenerd** [comment]
For what it's worth, I think it's relevant to keep MADR related to architecture. Architecture implies significance. Going through the labor of establishing a decision record is really only warranted when that decision will have a significant impact. Hence, why you wouldn't do it for "any" decision. While you **_could_** you probably **_shouldn't_** and most **_wouldn't_**.

**Comment by koppor** [comment]
IMHO, we changed everything in our developer branch, we need to check.
