### ISSUE TITLE
No Example for "Confirmation"

### ISSUE THREAD

**Issue by timo-abele** [adr/madr#135]
Hi, I'm confused what the headline "Confirmation" in the template means.

The explanation provided there is:
> {Describe how the implementation of/compliance with the ADR is confirmed. E.g., by a review or an ArchUnit test. Although we classify this element as optional, it is included in most ADRs.}

But a (code) review and an automated test are part of any feature anyway, right? And a review is done only once and cannot guarantee compliance in the future. Or is a regular review what is meant here? I'd love to read some concrete examples of this, but even though the section allegedly `is included in most ADRs`, I cannot find any examples, especially in this very repo: https://github.com/search?q=repo%3Aadr%2Fmadr+Confirmation&type=code 

Please provide some examples of how ADRs can be confirmed!

**Comment by socadk** [comment]
Thanks for the question @timo-abele. "Confirmation" is somewhat generic, less expressive and specific than other template section headings. The purpose of the section is to remind everybody who is involved that it is not enough to decide, design and implemenation actions are required to bring the AD to life. Architecture, design, and/or code reviews then confirm that this has actually happened, and that the resulting design and implementation are in line with the decision made. 

This blog post has a few more explanations (under "Validation"): https://medium.com/olzzio/the-markdown-adr-madr-template-explained-and-distilled-b67603ec95bb and this one has an example (look for the R in ecADR): https://ozimmer.ch/practices/2020/05/22/ADDefinitionOfDone.html

@koppor  your thoughts?
