### ISSUE TITLE
Broken 'examples.md' link on github.io

### ISSUE THREAD

**Issue by ggorlen** [adr/madr#137]
To reproduce, go to https://adr.github.io/madr/ and click on "For more examples see [examples](https://adr.github.io/madr/examples.md)":

![Screenshot showing examples.md link that leads to a 404](https://github.com/user-attachments/assets/9559dc0e-ed99-4415-9e09-e5b008b14ace)

This leads to a 404 and should be examples.html rather than examples.md. The trouble is, if you're browsing the file on GitHub itself, the examples.md link is correct and examples.html isn't, so the resolution isn't obvious to me offhand.

**Comment by SVendittelli** [comment]
I have run into this issue with jekyll before, I'll raise a PR to fix it.

**Comment by koppor** [comment]
Works as of today. Thank you for the report and the fix!
