### ISSUE TITLE
"edit this page" doesn't work

### ISSUE THREAD

**Issue by azarboon** [adr/madr#176]
When I click on "edit this page" I get error in the screenshot. I've got this error on all pages that I tried, including the main page. @koppor 

![image](https://github.com/user-attachments/assets/48eb1171-38eb-467f-9732-687e839fc763)

**Comment by azarboon** [comment]
@koppor the issue still persists

**Comment by koppor** [comment]
@azarboon Thank you for reporting. Should be fixed now - background on our branches is given at https://github.com/adr/madr#branches.
