### ISSUE TITLE
Add support for Status

### ISSUE THREAD

**Issue by koppor** [adr/madr#2]
Michael Nygard's template offers a Status field. See http://thinkrelevance.com/blog/2011/11/15/documenting-architecture-decisions. This should be supported by MADR, too. It should, however, be optional or less prominent to make it easier for newcomers. Maybe two variants of MADR?

[adr-tools](https://github.com/npryce/adr-tools) offers automatic setting of the status field. MADR, however, does not want to rely on tooling: It should be possible to create an ADR by just using copy'n'paste of `template.md`.

**Comment by koppor** [comment]
Also add date:

| Date | Status |
| -- | -- |
| 2016-02-13 | Accepted |

```
| Date | Status |
| -- | -- |
| 2016-02-13 | Accepted |

```

**Comment by koppor** [comment]
That should be placed one line separated after the heading:

```
# Use Markdown Architectural Decision Records

| Date | Status |
| -- | -- |
| 2016-02-13 | Accepted |

Should we record the architectural decisions made in this project?
And if we do, how to structure these recordings?
```

**Comment by koppor** [comment]
Tooling support is provided at https://github.com/npryce/adr-tools/pull/43. We "only" have to describe it in the `README.md` and possibly in the `template.md` file.

**Comment by pixelbrackets** [comment]
Hey,

I strongly support adding »status« and »date« information. 

However I suggest using sections instead of tables. Tables in markdown are harder to edit, than just plain text. They limit the space for any further information (e.g. links to other documents, regarding the status). And any table should contain more than just 1 row imho.

Concerning the status field I suggest this:

**Template**
Right below the title, prior the User Story

    **Status:** [Draft|Review|Accepted|Deprecated|Abandoned] - [optional addition like replacement ADR] 

**Example**

> **Status:** Deprecated - superseded by ADR 0001

Concerning the date field I suggest this:

**Template**
At the end of the document

    *YYYY-MM-DD* 

**Example**

> *2018-05-15*

**Comment by koppor** [comment]
The experiment at https://github.com/npryce/adr-tools/pull/43 was to see how the table works.

The initial status is not included in the template to keep it simple. I think that senior professionals are used to such flags, but beginners might be confused and lean against documenting something in MADR. Therefore, I wanted to keep the first lines of MADR pretty easy and the rest optional. We were also thinking of variants like `template.md` and `template-full.md`. May, `template-lean.md` and `template-full.md`. Maybe this could be a solution with both having newcomers not made afraid and professionals just using it?

There is a discussion going on whether a version control system solves the status of an ADR. Do git branches always correlate with the status of a document? Meaning, if one writes a specification using LaTeX in GitHub, does that file also need status flags?

I like your single status line. In the current version, we wanted to get rid of markdown emphasis such as `**`.

I wonder, what happens with multiple status lines? Like "refined-by", "see also", ...? I do not want to have multiple syntaxes for different cases. Therefore, the idea of the table was born. `adr-tools` just adds new lines at each status change. The user can then manually delete old status lines.

Regarding "Abandoned" and "Superseeded": In the former case, I would change the title of the ADR accordingly and keep the ADR itself in an updated state. Using a version control, one can dig deeper if one wants. If the abandoning is still interesting, it should be documented in the ADR why it was abandoned.

Similar for "Superseeded". The ADR should not kept as is, but modified according to the new setting. I am aware this could lead to inconsistencies. Especially, when [embedded ADRs](https://adr.github.io/e-adr/) point to an ADR. However, keeping outdated ADRs might confuse readers...

**Comment by koppor** [comment]
Related question: How to structure "Context and Problem Statement" and "[decision drivers | forces | facing]". Currently, they are only placeholders without any format requirement. Reason was to keep the number of lines very low until "Considered Options". However, when filling out the template, one asks himself: How to write that down? Should we offer an extended format at `template-full.md`?

**Comment by pixelbrackets** [comment]
Followup to the tables issue: Another reason why I would reject tables. Both fields in the table are optional. If an integrator would document the status only, a table with 1 row and 1 column would occur. That should not be a table. And it is even harder to explain to people why they should use this wiki-like characters to build a table.

Main reason why a single line or a section is better: The great advantage of markdown over other documentation formats like reST is the simple format. Easy to write AND easy to render. It is easy to parse a MD file and search for headlines or single lines. Eg. in my case I could build a web viewer which lists all ADRs with status "Draft" just by searching for "Status: [word]" right below the first headline. In a table with optional fields if have to write complex regex "If table with first row »Status« then use next line with first word… or of table with second row »Status« then…".

**Comment by koppor** [comment]
I think @snisnisniksonah also had more effort when implementing the tables in adr-tools.

The idea was that status is not mandatory. The initial state is always "Accepted". When using `adr-tools`,  the table is generated automatically and one "only" has to add `| date | status |`, which is easy to write, too 😇 

In case we switch to a single-line status, what about linked issues? There can be multiple ones. E.g., "refined-by". Even "contradicts" could exist...

Then, we are back with a heading, which is IMHO disturbing, because the information below `## Status`  is IMHO more an administrative one in contrast to the `Options` and `Pros and Cons`.

**Comment by miwurster** [comment]
Hey,

what about using badges to visualize the current status? 
Such as the build status of a project, we could simple put a "status" badge on top of each MADR.

Example:
![Image of Yaktocat](https://img.shields.io/badge/status-accepted-green.svg?style=flat-square)

**Comment by koppor** [comment]
+1 for badges

![status-accepted](https://img.shields.io/badge/status-accepted-brightgreen.svg?style=flat-square)

https://img.shields.io/badge/status-accepted-brightgreen.svg?style=flat-square

I am not sure how to deal with links. Think, we should introduce a separate `## Links` section to make links explicit?

**Comment by koppor** [comment]
Summary:

## Use badge

Example:  ![grafik](https://user-images.githubusercontent.com/1366654/36786999-ca368324-1c88-11e8-966d-56f25980fd76.png)

* Good, because plain markdown
* Good, because looks good
* Bad, because relies on the online service https://shields.io or local badges have to be generated.
* Bad, because not easy to write

## Use text line

Example: **Status:** Deprecated - superseded by ADR 0001

* Good, because plain markdown
* Good, because easy to write
* Bad, because uses space at the beginning. When users read MADR, they should directly dive into the context and problem and not into the status

## Use heading

Example:  ![grafik](https://user-images.githubusercontent.com/1366654/36787029-f5ea246c-1c88-11e8-9082-8e9531e4fac7.png)

* Good, because plain markdown
* Good, because easy to write
* Bad, because it uses much space: At least three lines: heading, status, separating empty line

## Use table

Example:  ![grafik](https://user-images.githubusercontent.com/1366654/36787043-0339a53e-1c89-11e8-8ebe-fb2a5752448c.png)

* Good, because history can be included
* Good, because multiple entries can be made
* Bad, because not covered by the CommonMark specification

**Comment by koppor** [comment]
Implemented. See also [ADR-0008](https://github.com/adr/madr/tree/master/docs/adr/0008-add-status-field.md).
