### ISSUE TITLE
Apply format of User Story field

### ISSUE THREAD

**Issue by pixelbrackets** [adr/madr#3]
The MADR template was pushed to the popular [architecture_decision_record](https://github.com/joelparkerhenderson/architecture_decision_record/) repository recently.

This template however has a different format for the User Story, than in documented in here…

Current MADR template:
* https://github.com/adr/madr/blob/master/template/template.md

    User Story: [ticket/issue-number] 

Pushed MADR template:
* https://github.com/joelparkerhenderson/architecture_decision_record/blob/master/adr_template_madr.md

    **User Story:** *[ticket/issue-number]* 

I like the pushed template. May I prepare a PR to add this change to this repository?

**Comment by pixelbrackets** [comment]
Sorry, its the other way around. The pushed template is older than the current state in this repository. As documented in https://github.com/pixelbrackets/madr/blob/master/CHANGELOG.md#130--2018-01-30 and commit https://github.com/adr/madr/commit/23cbc396d7e45148a9c32dfd9f66d42adfcf1c5b.

**Comment by koppor** [comment]
Yeah, I think @joelparkerhenderson was busy with https://github.com/SixArm/sixarm_ruby_markdown_table_of_contents and thus did not yet merge https://github.com/joelparkerhenderson/architecture_decision_record/pull/13

Some more background: We presented a paper at the [ZEUS workshop](http://zeus-workshop.eu/) and we incorporated feedback from the reviewers and the audience. The paper will be finally published in April.
