### ISSUE TITLE
Update recommended tooling for MADRs

### ISSUE THREAD

**Issue by Relequestual** [adr/madr#38]
The website lists a fork of `adr-tools` as the suggested tool for a more automated approach to using MADR, however the PR was rejected and closed, and the fork is now archived, marked as superseded by log4brains (https://github.com/thomvaill/log4brains).

As such, does it make sense to update the docs on the website to link straight there?

**Comment by koppor** [comment]
Add https://github.com/opinionated-digital-center/pyadr

**Comment by koppor** [comment]
Thank you for reporting it!

In case you find more tooling supporting MADR, please add it to https://github.com/adr/madr/blob/main/docs/tooling.md.
