### ISSUE TITLE
Remove "Sustainable Architectural Decisions" section

### ISSUE THREAD

**Issue by pixelbrackets** [adr/madr#4]
Proposal: Remove the section about "Sustainable Architectural Decisions" in the README.md (https://github.com/adr/madr/blob/master/README.md#background-information).

Reason: Alternatives to the MADR are linked in the example file already. Also they they are mentioned on summary pages like https://adr.github.io and https://github.com/joelparkerhenderson/architecture_decision_record. Adding a section about alternatives within the MADR readme just lengthens the document and distracts the reader.

Solution: Remove the section.

**Comment by koppor** [comment]
I removed the section and placed a link to adr.github.io as badge in the header:

![grafik](https://user-images.githubusercontent.com/1366654/36297152-64346d8e-12f1-11e8-88ed-e9de6a646277.png)

Not rendered well at the homepage, but accepatable:

![grafik](https://user-images.githubusercontent.com/1366654/36297175-7a95cbae-12f1-11e8-831a-a6c40f090ce2.png)
