### ISSUE TITLE
Add MADR version to the template?

### ISSUE THREAD

**Issue by pixelbrackets** [adr/madr#5]
Regarding #3 I just asked myself: How can I identify which version of MADR was used in a repository? 

Idea: Suggest as best practice to document the version of MADR which was used initially. For example in the [Initial decision file](https://github.com/adr/madr/blob/master/template/0000-use-markdown-architectural-decision-records.md). So that somebody who writes a ADR may decide "We will use MADR in version 1.3.0 to document ADRs" and later "We update all existing ADRs to follow MADR version 2.0.18" etc.
Alternative: Add the version to the template file.

What do you think?

**Comment by koppor** [comment]
I tried to include it in https://github.com/adr/madr/commit/297c9392047f4a7b9d6f1c2a01b09c0dba60c414.

I would not add the version to the template itself, because this bloats the template. In our setting, we even have a mix different MADR incarnations in our repository. 😇
