### ISSUE TITLE
Question: v2 vs. v3 

### ISSUE THREAD

**Issue by calebcartwright** [adr/madr#76]
Greetings 👋 First just want to thank you for these awesome projects!

My team has been looking for a way to capture our decisions more consistently, and your tools and the processes they facilitate seem like an absolutely perfect fit. I'd anticipated that given our size we'd likely need to end up with a mechanism to categorize records, and I was encouraged by what I saw in https://github.com/adr/madr/blob/main/docs/decisions/0010-support-categories.md. However, IIUC the categorization feature appears to be future looking (ostensibly in the v3 beta release) so I have a few questions I'm hoping you can assist me with:

* Is the tooling support for categorization feature described in 0010 targeted for v3, or are there plans to include it in a v2 release?
* Do you have a ballpark target for when you think a v3 release may be published to npm (even an explicitly beta/prerelease version)?
* If we start using the v2 tooling today, would we be able to update to v3 seamlessly, or at least in an automated fashion, or would some manual work and changes be required?

**Comment by koppor** [comment]
Thank you for your interest. The latest version is available at https://github.com/adr/madr/tree/main/template and documented at https://adr.github.io/madr/. 

> Is the tooling support for categorization feature described in 0010 targeted for v3, or are there plans to include it in a v2 release?

There is currently no tooling support. As far as I know, you can use [ADR Manager](https://marketplace.visualstudio.com/items?itemName=StevenChen.vscode-adr-manager) by @stevenchencb. It seems to support the multiple-directory use case. - It still sticks to the v2.1.2 version and I don't know about plans when and how it updates to 3.0.0.

Thus, I would really recommend using a text editor and the v3.0.0-beta.2 version.

> Do you have a ballpark target for when you think a v3 release may be published to npm (even an explicitly beta/prerelease version)?

There is no "real" need to install it using npm. You can start using the template file from https://github.com/adr/madr/blob/main/template/adr-template.md. "Just" copy it to the ADR you want to create and modify the text file. See https://adr.github.io/madr/#create-a-new-adr for a longer step-by-step howto. Please report back if that works for you.

In parallel, I will try to work on a 3.0.0 release. Currently, the issue https://github.com/adr/madr/issues/75 should be fixed for a 3.0.0 release. Currently, the only issue open. See https://github.com/adr/madr/milestone/1 for the complete list.

> If we start using the v2 tooling today, would we be able to update to v3 seamlessly, or at least in an automated fashion, or would some manual work and changes be required?

There is no tooling support planned for a migration. In case you want to contribute some, you are very welcome to do so! 

IMHO there are not much changes. The core idea to list different options inside one ADR is still kept. "Just" the syntax of the template and some namings changed. See https://github.com/adr/madr/blob/main/CHANGELOG.md#unreleased for a full list.

**Comment by calebcartwright** [comment]
That's most helpful, thank you! Fundamentally I was just trying to determine whether it might be easier/less work for us to wait until v3 was released, but it sounds like the upgrade shouldn't be too much of a hassle anyway.

> Please report back if that works for you.

Will do

> In parallel, I will try to work on a 3.0.0 release

Much appreciated, though no rush! :pray: 

> In case you want to contribute some, you are very welcome to do so!

I'm a bit stretched for time and already spread pretty thin across a number of open source projects, but this project intrigues me so I may see if I can carve out some time here and there to take a look.

**Comment by calebcartwright** [comment]
Closing as I feel the main question that was the gist of the issue has been answered, but may still post some follow up comments
