### ISSUE TITLE
Add branches to latest major versions

### ISSUE THREAD

**Issue by docwhat** [adr/madr#92]
Please consider adding a branch for each major version to allow easy linking to the correct documents and template. e.g., `stable-1`, `stable-2`, `stable-3`.

This would allow linking to (for example) the latest 2.x template without pulling in 3.x features until we are ready for them.

**Comment by koppor** [comment]
I read into https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow and created the following branches (see https://github.com/adr/madr/branches for the complete list)
		
- `main` always having the latest release
- `develop` for development - homepage generated using [netlify](https://www.netlify.com/) - hosted at https://develop--madr-develop.netlify.app/
- `gh-pages` for the homepage - being the stable homepage.
- `releases/v1`, `releases/v2`, `releases/v3` tracking releases of (past) major versions. Will create `develop/v1` and others as needed.
		
I looked at https://github.com/actions/setup-java for inspiration. They also seem to have "moving tags" for their major versions. I opted against it and keep the branches. There will be `develop/v1` in case there is a fix for the old versions.

I think, this should solve the issue. If not, feel free to reopen.

**Comment by koppor** [comment]
I removed branch `main`, because it causes confusion. All development should be in `develop`. That name should make clear that it's not the release version.
